language: node_js
node_js:
  - 12.18.3
before_script:
  - npm i -g npm@6.14.6
  - npm install
  - npm install --global expo-cli
cache:
  npm: false
script:
  - npm ci
  - npx jest --ci
jobs:
  include:
    - stage: deploy
      node_js: lts/*
      script:
        - npm ci
        - npx expo login -u $EXPO_USERNAME -p $EXPO_PASSWORD
        - npx expo publish --non-interactive
